/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Every readable recording in the directory. `no-store` -- the directory changes.
         */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description One recording's metadata -- cheaply, without building its index.
         */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Timeline
         * @description The scrubber's density background, downsampled to `buckets` columns if asked.
         */
        get: operations["get_timeline_api_sessions__session_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source
         * @description Source text plus its per-line execution heatmap.
         *
         *     The text comes from disk (the recording stores only a source *hash*, format 1.7). The
         *     current file is always served when readable; `available` says whether the heatmap aligns to
         *     it -- False when the file changed since recording -- so the UI can show the code and simply
         *     withhold the overlay rather than paint the heatmap over a different program.
         */
        get: operations["get_source_api_sessions__session_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/calltree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calltree
         * @description Stack mode: the frames live at `seq`, each with its parent so the UI can nest them.
         *
         *     A call *stack*, the familiar view. The call *tree* -- every call the program ever made --
         *     is the children endpoint below, expanded lazily one frame at a time.
         */
        get: operations["get_calltree_api_sessions__session_id__calltree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/calltree/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calltree Children
         * @description Tree mode: one page of a frame's direct children, for lazy expansion of the call tree.
         *
         *     This is the whole call tree, one level at a time -- click a call that returned 200k events
         *     ago and go there. `parent` omitted returns the forest *roots*, where the tree starts.
         *     Immutable per `(parent, after, limit)`: a finished recording's tree is fixed forever. An
         *     unknown `parent` simply has no children (an empty page), not an error.
         */
        get: operations["get_calltree_children_api_sessions__session_id__calltree_children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description The reconstructed instant at `seq`, cached hard and cancellable on disconnect.
         */
        get: operations["get_state_api_sessions__session_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Value
         * @description One captured value, expanded one level -- the lazy click-to-expand of a variable.
         */
        get: operations["get_value_api_sessions__session_id__value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Diff
         * @description What changed from `seq-1` to `seq` -- the variable diff, read from the day-16 deltas.
         *
         *     Immutable per `seq` (a finished recording's transition never changes), so it caches like
         *     `/state`: a repeat drag over the same instant is a 304.
         */
        get: operations["get_diff_api_sessions__session_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Step
         * @description Step from `seq`: `mode` in {into, over, out}, `dir` in {forward, backward}.
         *
         *     A boundary (start/end of the recording, or a truncated tail) comes back as an `edge`, not
         *     an error -- it is the value the UI renders as a disabled button.
         */
        get: operations["get_step_api_sessions__session_id__step_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Queries
         * @description Every query the engine offers, with its argument schema, so the UI builds forms from it.
         *
         *     Global, not per-session: the catalogue is the same for every recording. The day-28 registry
         *     makes it enumerable without running anything -- add a query there and it appears here, and in
         *     the panel, with no frontend change. That decoupling is the endpoint's whole reason to exist.
         */
        get: operations["list_queries_api_queries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Query
         * @description Run one registered query and return a page of instants.
         *
         *     A query that ran and found nothing is an empty page, not an error. An *unknown name* is
         *     UNKNOWN_QUERY, malformed *args* are BAD_REQUEST, and a query that rejects its input
         *     (`UnknownName`, a variable that was never recorded) bubbles to NOT_FOUND via the error
         *     handler -- three different mistakes with three different fixes, as the codes promise.
         */
        post: operations["run_query_api_sessions__session_id__query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArgSpec */
        ArgSpec: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Required */
            required: boolean;
        };
        /** CallFrame */
        CallFrame: {
            /** Frame Id */
            frame_id: number;
            /** Function */
            function: string;
            /** File */
            file: string;
            /** Entry Seq */
            entry_seq: number;
            /** Exit Seq */
            exit_seq: number | null;
            exit_kind: components["schemas"]["ExitKind"];
            /** Parent Frame Id */
            parent_frame_id: number | null;
        };
        /** CallTree */
        CallTree: {
            /** Frames */
            frames: components["schemas"]["CallFrame"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /**
         * ChangeKind
         * @description How a binding changed between two instants -- the three colours a diff panel paints.
         * @enum {string}
         */
        ChangeKind: "added" | "removed" | "modified";
        /** Diff */
        Diff: {
            /** Seq */
            seq: number;
            /** Changes */
            changes: components["schemas"]["VarChange"][];
        };
        /** ExceptionInfo */
        ExceptionInfo: {
            /** Exc Type */
            exc_type: string;
            /** Raised At Seq */
            raised_at_seq: number;
            /** Message */
            message?: string | null;
        };
        /**
         * ExitKind
         * @description How a frame ended -- the single most useful thing a call tree colours.
         *
         *     `raised` is a frame CPython unwound because of an exception (day-6's UNWIND), painted
         *     distinctly so the tree answers "where did it blow up?" at a glance. `open` is a frame that
         *     never returned in the recording -- still live at the end, a suspended generator, or a
         *     crash-truncated tail (`exit_seq IS NULL`); not an error, just not-yet-returned.
         * @enum {string}
         */
        ExitKind: "returned" | "raised" | "open";
        /** Frame */
        Frame: {
            /** Frame Id */
            frame_id: number;
            /** Function */
            function: string;
            /** File */
            file: string;
            /** Lineno */
            lineno: number;
            /** Suspended */
            suspended: boolean;
            /** Variables */
            variables: components["schemas"]["Variable"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LineHeat */
        LineHeat: {
            /** Lineno */
            lineno: number;
            /** Count */
            count: number;
        };
        /** QueryDescriptor */
        QueryDescriptor: {
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            /** Args */
            args: components["schemas"]["ArgSpec"][];
        };
        /** QueryHit */
        QueryHit: {
            /** Seq */
            seq: number;
            /** File */
            file?: string | null;
            /** Lineno */
            lineno?: number | null;
            /** Function */
            function?: string | null;
            /** Value Preview */
            value_preview?: string | null;
            /** Note */
            note?: string | null;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Name */
            name: string;
            /** Args */
            args: {
                [key: string]: string | number | boolean | null;
            };
            /** Cursor */
            cursor?: number | null;
            /** Limit */
            limit?: number | null;
        };
        /** QueryResult */
        QueryResult: {
            /** Hits */
            hits: components["schemas"]["QueryHit"][];
            /** Next Cursor */
            next_cursor: number | null;
            /** Partial */
            partial: boolean;
        };
        /** SessionMeta */
        SessionMeta: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Event Count */
            event_count: number;
            /** Truncated */
            truncated: boolean;
            /** Indexed */
            indexed: boolean;
            /** Format Version */
            format_version: string;
            /** Keyframe Count */
            keyframe_count: number;
            /** Python Version */
            python_version?: string | null;
            /** Recorded At */
            recorded_at?: string | null;
        };
        /** SessionSummary */
        SessionSummary: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Event Count */
            event_count: number;
            /** Truncated */
            truncated: boolean;
            /** Indexed */
            indexed: boolean;
        };
        /** Source */
        Source: {
            /** File */
            file: string;
            /** Lines */
            lines: string[];
            /** Heatmap */
            heatmap: components["schemas"]["LineHeat"][];
            /** Available */
            available: boolean;
        };
        /** State */
        State: {
            /** Seq */
            seq: number;
            /** Current Frame Id */
            current_frame_id: number;
            /** Frames */
            frames: components["schemas"]["Frame"][];
            /** Truncated */
            truncated: boolean;
            exception?: components["schemas"]["ExceptionInfo"] | null;
        };
        /**
         * StepEdge
         * @description Why a step did not move -- a value the UI renders (a disabled button), not an error.
         * @enum {string}
         */
        StepEdge: "beginning" | "end" | "lost_tail";
        /** StepResult */
        StepResult: {
            /** Seq */
            seq: number | null;
            edge: components["schemas"]["StepEdge"] | null;
        };
        /** Timeline */
        Timeline: {
            /** Buckets */
            buckets: components["schemas"]["TimelineBucket"][];
            /** Total Events */
            total_events: number;
            /** Truncated */
            truncated: boolean;
        };
        /** TimelineBucket */
        TimelineBucket: {
            /** First Seq */
            first_seq: number;
            /** Event Count */
            event_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Value */
        Value: {
            /** Preview */
            preview: string;
            /** Kind */
            kind: string;
            /** Truncated */
            truncated: boolean;
            /** Children */
            children?: components["schemas"]["ValueChild"][] | null;
        };
        /** ValueChild */
        ValueChild: {
            /** Key */
            key: string;
            /** Preview */
            preview: string;
            /** Ref */
            ref: number | null;
            /** Has Children */
            has_children: boolean;
        };
        /** VarChange */
        VarChange: {
            /** Frame Id */
            frame_id: number;
            /** Name */
            name: string;
            kind: components["schemas"]["ChangeKind"];
            /** Old */
            old?: string | null;
            /** New */
            new?: string | null;
        };
        /** Variable */
        Variable: {
            /** Name */
            name: string;
            /** Preview */
            preview: string;
            /** Ref */
            ref: number | null;
            /** Has Children */
            has_children: boolean;
            /** Truncated */
            truncated: boolean;
            /** Obj Id */
            obj_id?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_api_sessions__session_id__timeline_get: {
        parameters: {
            query?: {
                buckets?: number | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_sessions__session_id__source_get: {
        parameters: {
            query: {
                file: string;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calltree_api_sessions__session_id__calltree_get: {
        parameters: {
            query: {
                seq: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallTree"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calltree_children_api_sessions__session_id__calltree_children_get: {
        parameters: {
            query?: {
                parent?: number | null;
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallTree"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_sessions__session_id__state_get: {
        parameters: {
            query: {
                seq: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["State"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_value_api_sessions__session_id__value_get: {
        parameters: {
            query: {
                ref: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Value"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diff_api_sessions__session_id__diff_get: {
        parameters: {
            query: {
                seq: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_step_api_sessions__session_id__step_get: {
        parameters: {
            query: {
                seq: number;
                dir?: string;
                mode?: string;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_queries_api_queries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryDescriptor"][];
                };
            };
        };
    };
    run_query_api_sessions__session_id__query_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
